gamemode=adventure
white-list=false
spawn-protection=0
difficulty=3
max-players=100
motd=Abellan minecraft server
world-border=100
simulation-distance=5
view-distance=16
enforce-secure-profile=false
player-idle-timeout=0
entity-broadcast-range-percentage=100
sync-chunk-writes=false
